-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 02, 2024 at 07:10 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `training_jeelp`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `desc` text NOT NULL,
  `price` decimal(7,2) NOT NULL,
  `rrp` decimal(7,2) NOT NULL DEFAULT 0.00,
  `quantity` int(11) NOT NULL,
  `img` text NOT NULL,
  `date_added` datetime NOT NULL DEFAULT current_timestamp(),
  `brand` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `desc`, `price`, `rrp`, `quantity`, `img`, `date_added`, `brand`) VALUES
(1, 'Apple iPhone 13', '<p>The Apple iPhone 13 brings cutting-edge technology in a sleek package. With its innovative features and elegant design, it redefines what a smartphone can be.</p>\r\n\r\n<h3>Key Features:</h3>\r\n\r\n<ul>\r\n\r\n<li>Unlock with Face ID, supported by accelerometer, gyro, proximity, compass, barometer, and Ultra Wideband (UWB) technology.</li>\r\n\r\n<li>Enjoy a long-lasting battery life that keeps up with your busy day.</li>\r\n\r\n<li>Experience seamless performance with 128GB internal memory and 4GB RAM.</li>\r\n\r\n</ul>\r\n\r\n<h3>Dimensions and Build:</h3>\r\n\r\n<ul>\r\n\r\n<li>Compact dimensions of 146.7 x 71.5 x 7.7 mm (5.78 x 2.81 x 0.30 in) ensure comfortable handling.</li>\r\n\r\n<li>Weighing just 174 g (6.14 oz), its lightweight and easy to carry.</li>\r\n\r\n<li>Premium build quality featuring a glass front and back, protected by Corning-made glass, and an aluminum frame for durability.</li>\r\n\r\n</ul>\r\n', '379.70', '0.00', 10, 'apple-iphone-13.jpg', '2024-04-02 15:39:07', 'Apple'),
(2, 'Apple iPhone 14', '<p>The Apple iPhone 14 represents the pinnacle of smartphone technology, combining cutting-edge features with sleek design.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock with Face ID, supported by accelerometer, gyro, proximity, compass, barometer, and Ultra Wideband (UWB) technology.</li>\r\n\r\n        <li>Exceptional battery life to keep you powered throughout the day.</li>\r\n\r\n        <li>Ample storage with 256GB internal memory and 6GB RAM for seamless multitasking.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 150.2 x 71.5 x 7.7 mm (5.91 x 2.81 x 0.30 in) ensure a comfortable grip.</li>\r\n\r\n        <li>Lightweight design weighing only 180 g (6.35 oz) for easy portability.</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning-made glass, and an aluminum frame.</li>\r\n\r\n    </ul>\r\n', '999.99', '0.00', 10, 'apple-iphone-14.jpg', '2024-04-02 16:04:39', 'Apple'),
(3, 'Apple iPhone 15 Pro', '<p>The Apple iPhone 15 Pro sets new standards for excellence in smartphone technology, delivering unparalleled performance and innovation.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Advanced Face ID for secure authentication, supported by a suite of sensors including accelerometer, gyro, proximity, compass, barometer, and Ultra Wideband (UWB) technology.</li>\r\n\r\n        <li>Exceptional battery life to keep you powered throughout your day.</li>\r\n\r\n        <li>Generous storage capacity with 512GB internal memory and 8GB RAM for seamless multitasking and storage of your precious memories.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Elegant dimensions of 153.5 x 73.7 x 7.5 mm (6.04 x 2.90 x 0.30 in) ensure a perfect balance of form and function.</li>\r\n\r\n        <li>Lightweight design weighing only 187 g (6.60 oz) for effortless portability.</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning-made glass, and an aluminum frame, exuding sophistication and durability.</li>\r\n\r\n    </ul>\r\n', '1299.99', '0.00', 10, 'apple-iphone-15-pro.jpg', '2024-04-02 16:07:30', 'Apple'),
(4, 'Samsung Galaxy M55', '<p>The Samsung Galaxy M55 is a powerful and stylish smartphone designed to enhance your mobile experience.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock with advanced facial recognition technology for convenient and secure access to your device.</li>\r\n\r\n        <li>Long-lasting battery life ensures you stay connected throughout the day.</li>\r\n\r\n        <li>Spacious storage with 256GB internal memory and 8GB RAM, providing ample space for your apps, photos, and media.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 158.5 x 73.6 x 7.9 mm (6.24 x 2.90 x 0.31 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Lightweight design weighing just 174 g (6.14 oz) for effortless portability.</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '899.99', '0.00', 10, 'samsung-galaxy-m55.jpg', '2024-04-02 16:11:47', 'Samsung'),
(5, 'Samsung Galaxy A55', '<p>The Samsung Galaxy A55 is a versatile and feature-rich smartphone designed to meet all your mobile needs.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with facial recognition technology.</li>\r\n\r\n        <li>Enjoy all-day battery life, ensuring you stay connected when you need it most.</li>\r\n\r\n        <li>With 128GB internal storage and 6GB RAM, youll have plenty of space for your apps, photos, and videos.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 158.5 x 73.6 x 7.9 mm (6.24 x 2.90 x 0.31 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just 172 g (6.07 oz), its lightweight and easy to carry.</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '699.99', '0.00', 10, 'samsung-galaxy-a55.jpg', '2024-04-02 16:14:36', 'Samsung'),
(6, 'Samsung Galaxy S24 Ultra', '<p>The Samsung Galaxy S24 Ultra is the pinnacle of smartphone technology, offering cutting-edge features and unrivaled performance.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock with lightning-fast facial recognition or ultrasonic fingerprint sensor, ensuring your device stays secure.</li>\r\n\r\n        <li>Experience unparalleled battery life that keeps you powered throughout your day and beyond.</li>\r\n\r\n        <li>With a massive 1TB internal storage and 16GB RAM, youll have ample space for all your apps, games, and media.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 164.3 x 76.6 x 8.9 mm (6.47 x 3.02 x 0.35 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Despite its powerful features, it remains lightweight at 220 g (7.76 oz).</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning Gorilla Glass Victus, and an aluminum frame for added durability.</li>\r\n\r\n    </ul>\r\n', '1499.99', '0.00', 10, 'samsung-galaxy-s24-ultra.jpg', '2024-04-02 16:17:10', 'Samsung'),
(7, 'Nokia C210', '<p>The Nokia C210 is a reliable and affordable feature phone that keeps you connected without the distractions of a smartphone.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Effortlessly make calls and send texts with its intuitive keypad and user-friendly interface.</li>\r\n\r\n        <li>Enjoy extended battery life, so you can stay connected for longer periods without needing to recharge.</li>\r\n\r\n        <li>Compact and lightweight design makes it easy to carry in your pocket or bag.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Compact dimensions of 115.2 x 49.8 x 14.3 mm (4.54 x 1.96 x 0.56 in) ensure comfortable handling.</li>\r\n\r\n        <li>Weighing just 84.8 g (2.99 oz), its lightweight and portable.</li>\r\n\r\n        <li>Durable construction designed to withstand everyday wear and tear.</li>\r\n\r\n    </ul>\r\n', '49.99', '0.00', 10, 'nokia-c210.jpg', '2024-04-02 16:23:47', 'Nokia'),
(8, 'Nokia G310', '<p>The Nokia G310 is a versatile and powerful smartphone designed to enhance your mobile experience.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with its responsive fingerprint sensor.</li>\r\n\r\n        <li>Enjoy all-day battery life, ensuring you stay connected throughout your busy day.</li>\r\n\r\n        <li>With 128GB internal storage and 6GB RAM, youll have plenty of space for your apps, photos, and videos.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 164.9 x 76.2 x 9.5 mm (6.49 x 3.00 x 0.37 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just 191 g (6.74 oz), its lightweight and easy to carry.</li>\r\n\r\n        <li>Premium build quality featuring a durable glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '299.99', '0.00', 10, 'nokia-g310.jpg', '2024-04-02 16:30:29', 'Nokia'),
(9, 'Nokia 105 4G (2023)', '<p>The Nokia 105 4G (2023) is a reliable and affordable feature phone that keeps you connected with the latest 4G technology.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Stay connected with high-speed 4G connectivity for calls, texts, and basic internet browsing.</li>\r\n\r\n        <li>Long-lasting battery life ensures you stay connected throughout the day without needing to recharge frequently.</li>\r\n\r\n        <li>Compact and lightweight design with an easy-to-use keypad makes it perfect for everyday use.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Compact dimensions of 121.6 x 50.3 x 14.9 mm (4.79 x 1.98 x 0.59 in) ensure comfortable handling.</li>\r\n\r\n        <li>Weighing just 85.5 g (3.02 oz), its lightweight and portable.</li>\r\n\r\n        <li>Durable construction designed to withstand everyday use.</li>\r\n\r\n    </ul>\r\n', '29.99', '0.00', 10, 'nokia-105-4g-2023.jpg', '2024-04-02 16:33:42', 'Nokia'),
(10, 'Oppo F25 Pro', '<p>The Oppo F25 Pro is a sleek and powerful smartphone designed to elevate your mobile experience.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the in-display fingerprint sensor.</li>\r\n\r\n        <li>Experience smooth performance and seamless multitasking with its powerful processor and ample RAM.</li>\r\n\r\n        <li>Immerse yourself in stunning visuals and vibrant colors with its high-resolution display.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 160.2 x 73.8 x 7.9 mm (6.31 x 2.91 x 0.31 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Lightweight design weighing just 175 g (6.17 oz) for effortless portability.</li>\r\n\r\n        <li>Premium build quality featuring a glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '499.99', '0.00', 10, 'oppo-f25-pro.jpg', '2024-04-02 16:36:34', 'Oppo'),
(11, 'Oppo Reno 11', '<p>The Oppo Reno 11 is a stylish and feature-packed smartphone designed to meet your everyday needs.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the in-display fingerprint sensor.</li>\r\n\r\n        <li>Enjoy immersive multimedia experiences with its vibrant display and powerful speakers.</li>\r\n\r\n        <li>Capture stunning photos and videos with its high-resolution camera system.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 160.3 x 74.3 x 7.9 mm (6.31 x 2.93 x 0.31 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Lightweight design weighing just 172 g (6.07 oz) for easy portability.</li>\r\n\r\n        <li>Durable build quality featuring a glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '699.99', '0.00', 10, 'oppo-reno11.jpg', '2024-04-02 16:42:23', 'Oppo'),
(12, 'Oppo Find X7 Ultra', '<p>The Oppo Find X7 Ultra is a flagship smartphone that redefines mobile technology with its innovative features and premium design.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your device swiftly and securely with the in-display fingerprint sensor or advanced facial recognition technology.</li>\r\n\r\n        <li>Experience stunning visuals and vibrant colors on its high-resolution display, perfect for gaming, streaming, and productivity.</li>\r\n\r\n        <li>Capture breathtaking photos and videos with its advanced camera system, featuring multiple lenses and AI-powered enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 163.4 x 74 x 8.3 mm (6.43 x 2.91 x 0.33 in) ensure a comfortable grip and elegant aesthetics.</li>\r\n\r\n        <li>Weighing just 205 g (7.23 oz), it strikes a perfect balance between portability and durability.</li>\r\n\r\n        <li>Premium build quality featuring a glass front and back, protected by Corning Gorilla Glass Victus, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '1299.99', '0.00', 10, 'oppo-find-x7-ultra.jpg', '2024-04-02 16:44:22', 'Oppo'),
(13, 'vivo V30 Lite (ME)', '<p>The vivo V30 Lite (ME) is a stylish and affordable smartphone that offers great performance and features.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone effortlessly with the responsive fingerprint sensor.</li>\r\n\r\n        <li>Enjoy immersive visuals and vibrant colors on its high-definition display, perfect for watching videos and browsing the web.</li>\r\n\r\n        <li>Capture stunning photos and selfies with its advanced camera system, featuring AI enhancements for perfect shots every time.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 159.6 x 75.4 x 8.2 mm (6.28 x 2.97 x 0.32 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just 177 g (6.24 oz), its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a glass front and back, protected by Corning Gorilla Glass, and a sturdy plastic frame.</li>\r\n\r\n    </ul>\r\n', '299.99', '0.00', 10, 'vivo-v30-lite-me.jpg', '2024-04-02 16:48:23', 'vivo'),
(14, 'vivo V30', '<p>The vivo V30 is a premium smartphone that combines elegant design with powerful performance.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with the in-display fingerprint sensor.</li>\r\n\r\n        <li>Experience stunning visuals and vibrant colors on its high-resolution display, perfect for watching videos and gaming.</li>\r\n\r\n        <li>Capture every moment with precision and clarity using its advanced camera system, featuring multiple lenses and AI enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of 158.7 x 73.4 x 7.8 mm (6.25 x 2.89 x 0.31 in) make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just 169 g (5.96 oz), its lightweight and easy to carry.</li>\r\n\r\n        <li>Premium build quality featuring a glass front and back, protected by Corning Gorilla Glass, and a sturdy aluminum frame.</li>\r\n\r\n    </ul>\r\n', '599.99', '0.00', 10, 'vivo-v30.jpg', '2024-04-02 16:50:43', 'vivo'),
(15, 'Realme 12x', '<p>The Realme 12x is a feature-packed smartphone that offers excellent performance and value for money.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with the fingerprint sensor or face unlock feature.</li>\r\n\r\n        <li>Enjoy immersive visuals on its large, high-resolution display, perfect for watching videos and gaming.</li>\r\n\r\n        <li>Capture stunning photos with its advanced camera system, featuring multiple lenses and AI enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of [Dimensions] make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just [Weight], its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a [Material] body.</li>\r\n\r\n    </ul>\r\n', '399.99', '0.00', 10, 'realme-12x.jpg', '2024-04-02 16:53:53', 'Realme'),
(16, 'Realme 12 Pro+', '<p>The Realme 12 Pro+ is a flagship smartphone that offers top-notch performance and cutting-edge features.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with the in-display fingerprint sensor or facial recognition technology.</li>\r\n\r\n        <li>Experience stunning visuals on its large, high-resolution display, perfect for gaming and multimedia.</li>\r\n\r\n        <li>Capture breathtaking photos and videos with its advanced camera system, featuring multiple lenses and AI enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of [Dimensions] make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just [Weight], its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a [Material] body.</li>\r\n\r\n    </ul>\r\n', '799.99', '0.00', 10, 'realme-12-pro-plus.jpg', '2024-04-02 16:56:13', 'Realme'),
(17, 'Realme Note 50', '<p>The Realme Note 50 is a powerful mid-range smartphone that offers impressive features at an affordable price.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the rear-mounted fingerprint sensor.</li>\r\n\r\n        <li>Enjoy immersive visuals on its large, high-definition display, perfect for streaming movies and gaming.</li>\r\n\r\n        <li>Capture stunning photos with its versatile camera system, featuring AI enhancements for perfect shots every time.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of [Dimensions] make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just [Weight], its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a [Material] body.</li>\r\n\r\n    </ul>\r\n', '299.99', '0.00', 10, 'realme-note-50.jpg', '2024-04-02 16:59:29', 'Realme'),
(18, 'OnePlus 12R', '<p>The OnePlus 12R is a flagship smartphone that delivers exceptional performance and innovative features.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the in-display fingerprint sensor or facial recognition.</li>\r\n\r\n        <li>Experience stunning visuals on its large, high-resolution display, perfect for gaming and multimedia.</li>\r\n\r\n        <li>Capture professional-grade photos and videos with its advanced camera system, featuring Hasselblad optics and AI enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of [Dimensions] make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just [Weight], its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a [Material] body.</li>\r\n\r\n    </ul>\r\n', '899.99', '0.00', 10, 'oneplus-12r.jpg', '2024-04-02 17:02:19', 'OnePlus'),
(19, 'OnePlus Nord 3', '<p>The OnePlus Nord 3 is a mid-range smartphone that offers a perfect balance of performance and affordability.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the in-display fingerprint sensor or facial recognition.</li>\r\n\r\n        <li>Enjoy immersive visuals on its large, high-resolution display, perfect for streaming and gaming.</li>\r\n\r\n        <li>Capture stunning photos with its versatile camera system, featuring multiple lenses and AI enhancements.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Sleek dimensions of [Dimensions] make it comfortable to hold and use.</li>\r\n\r\n        <li>Weighing just [Weight], its lightweight and easy to carry.</li>\r\n\r\n        <li>Durable build quality with a [Material] body.</li>\r\n\r\n    </ul>\r\n', '499.99', '0.00', 10, 'oneplus-nord-3.jpg', '2024-04-02 17:04:58', 'OnePlus'),
(20, 'OnePlus Nord CE4', '<p>The OnePlus Nord CE4 is a budget-friendly smartphone that offers great performance and essential features.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone quickly and securely with the rear-mounted fingerprint sensor.</li>\r\n\r\n        <li>Enjoy immersive visuals on its large, high-definition display, perfect for watching videos and browsing the web.</li>\r\n\r\n        <li>Capture stunning photos with its versatile camera system, featuring AI enhancements for optimal results.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Dimensions: [Dimensions] mm (length) x [Dimensions] mm (width) x [Dimensions] mm (height)</li>\r\n\r\n        <li>Weight: [Weight] grams</li>\r\n\r\n        <li>Build: [Material] construction</li>\r\n\r\n    </ul>\r\n', '299.99', '0.00', 10, 'oneplus-nord-ce4.jpg', '2024-04-02 17:07:44', 'OnePlus'),
(21, 'Motorola Moto G Power (2024)', '<p>The Motorola Moto G Power (2024) is a reliable and affordable smartphone designed to keep you connected and productive.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Unlock your phone swiftly and securely with the rear-mounted fingerprint sensor.</li>\r\n\r\n        <li>Experience vibrant visuals on its large, high-definition display, perfect for streaming and browsing.</li>\r\n\r\n        <li>Capture stunning photos and videos with its versatile camera system, optimized for various lighting conditions.</li>\r\n\r\n        <li>Enjoy all-day battery life with its long-lasting battery, ensuring you stay connected without interruptions.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Dimensions: [Dimensions] mm (length) x [Dimensions] mm (width) x [Dimensions] mm (height)</li>\r\n\r\n        <li>Weight: [Weight] grams</li>\r\n\r\n        <li>Build: Durable [Material] construction</li>\r\n\r\n    </ul>\r\n', '249.99', '0.00', 10, 'motorola-moto-g-power-2024.jpg', '2024-04-02 17:12:28', 'Motorola'),
(22, 'Motorola Moto G34', '<p>The Motorola Moto G34 is a feature-rich smartphone designed to deliver exceptional performance and user experience.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>6.8-inch Full HD+ display for immersive viewing experiences.</li>\r\n\r\n        <li>Qualcomm Snapdragon 695 processor for smooth multitasking and gaming.</li>\r\n\r\n        <li>Triple rear camera setup with a 64MP main sensor for stunning photos.</li>\r\n\r\n        <li>Large 5000mAh battery for all-day usage.</li>\r\n\r\n        <li>Water-repellent design for added durability.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Dimensions: 170 x 77.2 x 9.2 mm (6.69 x 3.04 x 0.36 in)</li>\r\n\r\n        <li>Weight: 210 grams</li>\r\n\r\n        <li>Build: Glass front, plastic frame, plastic back</li>\r\n\r\n    </ul>\r\n', '349.99', '0.00', 50, 'motorola-moto-g34.jpg', '2024-04-02 17:15:28', 'Motorola'),
(23, 'Google Pixel 6', '<p>The Google Pixel 6 is a flagship smartphone that redefines mobile photography and performance.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>6.4-inch Full HD+ OLED display for vibrant visuals.</li>\r\n\r\n        <li>Google Tensor chip for lightning-fast performance and AI capabilities.</li>\r\n\r\n        <li>Dual rear camera system with a 50MP main sensor and advanced computational photography.</li>\r\n\r\n        <li>Android 12 with exclusive Pixel features for a seamless user experience.</li>\r\n\r\n        <li>Large 4500mAh battery with fast charging support.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Dimensions: 158.6 x 74.8 x 8.9 mm (6.24 x 2.94 x 0.35 in)</li>\r\n\r\n        <li>Weight: 207 grams</li>\r\n\r\n        <li>Build: Glass front, aluminum frame, glass back</li>\r\n\r\n    </ul>\r\n', '699.99', '0.00', 20, 'google-pixel-6.jpg', '2024-04-02 17:19:11', 'Google'),
(24, 'Google Pixel 8 Pro', '<p>The Google Pixel 8 Pro is a premium flagship smartphone that combines cutting-edge technology with exceptional camera capabilities.</p>\r\n\r\n    <h3>Key Features:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>6.8-inch Quad HD+ OLED display for stunning visuals.</li>\r\n\r\n        <li>Google Tensor 3 chip for unparalleled performance and AI capabilities.</li>\r\n\r\n        <li>Triple rear camera system with advanced computational photography and 108MP main sensor.</li>\r\n\r\n        <li>Android 13 with exclusive Pixel features for a seamless user experience.</li>\r\n\r\n        <li>Large 5000mAh battery with fast charging and wireless charging support.</li>\r\n\r\n    </ul>\r\n\r\n    <h3>Dimensions and Build:</h3>\r\n\r\n    <ul>\r\n\r\n        <li>Dimensions: [Dimensions] mm (length) x [Dimensions] mm (width) x [Dimensions] mm (height)</li>\r\n\r\n        <li>Weight: [Weight] grams</li>\r\n\r\n        <li>Build: Glass front and back, aluminum frame</li>\r\n\r\n    </ul>\r\n', '999.99', '0.00', 20, 'google-pixel-8-pro.jpg', '2024-04-02 17:21:14', 'Google');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
